language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: SKIP_PHPSTAN=true
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - if [ "$SKIP_PHPSTAN" == "true" ]; then composer remove --dev --no-update phpstan/phpstan phpstan/phpstan-phpunit; fi
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/coverage-check coverage.xml 100
  - vendor/bin/phpcs -np --colors
  - if [ "$SKIP_PHPSTAN" != "true" ]; then vendor/bin/phpstan analyse --no-interaction; fi

after_script:
  - bash <(curl -s https://codecov.io/bash)
