FactorioItemBrowser\Api\Client\Entity\ExportJob:
  access_type: public_method
  exclusion_policy: all
  properties:
    status:
      type: string
    creationTime:
      type: DateTime<'Y-m-d\TH:i:sP'>
    exportTime:
      type: DateTime<'Y-m-d\TH:i:sP'>
    importTime:
      type: DateTime<'Y-m-d\TH:i:sP'>
    errorMessage:
      type: string
