FactorioItemBrowser\Api\Client\Entity\ValidatedMod:
  access_type: public_method
  exclusion_policy: all
  properties:
    name:
      type: string
    version:
      type: string
    issueType:
      type: string
    issueDependency:
      type: string
