FactorioItemBrowser\Api\Client\Entity\Machine:
  access_type: public_method
  exclusion_policy: all
  properties:
    craftingSpeed:
      type: float
    numberOfItemSlots:
      type: integer
    numberOfFluidInputSlots:
      type: integer
    numberOfFluidOutputSlots:
      type: integer
    numberOfModuleSlots:
      type: integer
    energyUsage:
      type: float
    energyUsageUnit:
      type: string
