FactorioItemBrowser\Api\Client\Entity\RecipeWithExpensiveVersion:
  access_type: public_method
  exclusion_policy: all
  properties:
    expensiveVersion:
      type: FactorioItemBrowser\Api\Client\Entity\Recipe
