FactorioItemBrowser\Api\Client\Entity\GenericEntityWithRecipes:
  access_type: public_method
  exclusion_policy: all
  properties:
    recipes:
      type: array<FactorioItemBrowser\Api\Client\Entity\RecipeWithExpensiveVersion>
    totalNumberOfRecipes:
      type: int
