FactorioItemBrowser\Api\Client\Request\Recipe\RecipeListRequest:
  access_type: public_method
  exclusion_policy: all
  properties:
    numberOfResults:
      type: integer
    indexOfFirstResult:
      type: integer
