FactorioItemBrowser\Api\Client\Request\Item\ItemIngredientRequest:
  access_type: public_method
  exclusion_policy: all
  properties:
    type:
      type: string
    name:
      type: string
    numberOfResults:
      type: integer
    indexOfFirstResult:
      type: integer
