FactorioItemBrowser\Api\Client\Request\Item\ItemRandomRequest:
  access_type: public_method
  exclusion_policy: all
  properties:
    numberOfResults:
      type: integer
    numberOfRecipesPerResult:
      type: integer
