FactorioItemBrowser\Api\Client\Request\Search\SearchQueryRequest:
  exclusion_policy: all
  properties:
    query:
      type: string
    numberOfResults:
      type: integer
    indexOfFirstResult:
      type: integer
    numberOfRecipesPerResult:
      type: integer
