FactorioItemBrowser\Api\Client\Response\Recipe\RecipeDetailsResponse:
  exclusion_policy: all
  properties:
    recipes:
      type: array<FactorioItemBrowser\Api\Client\Transfer\RecipeWithExpensiveVersion>
