FactorioItemBrowser\Api\Client\Response\Item\ItemListResponse:
  access_type: public_method
  exclusion_policy: all
  properties:
    items:
      type: array<FactorioItemBrowser\Api\Client\Entity\GenericEntityWithRecipes>
    totalNumberOfResults:
      type: integer
