FactorioItemBrowser\Api\Client\Response\Recipe\RecipeDetailsResponse:
  access_type: public_method
  exclusion_policy: all
  properties:
    recipes:
      type: array<FactorioItemBrowser\Api\Client\Entity\RecipeWithExpensiveVersion>
