FactorioItemBrowser\Api\Client\Response\Item\ItemIngredientResponse:
  access_type: public_method
  exclusion_policy: all
  properties:
    item:
      type: FactorioItemBrowser\Api\Client\Entity\GenericEntityWithRecipes
