FactorioItemBrowser\Api\Client\Response\Search\SearchQueryResponse:
  exclusion_policy: all
  properties:
    results:
      type: array<FactorioItemBrowser\Api\Client\Transfer\GenericEntityWithRecipes>
    totalNumberOfResults:
      type: integer
