FactorioItemBrowser\Api\Client\Response\Generic\GenericDetailsResponse:
  access_type: public_method
  exclusion_policy: all
  properties:
    entities:
      type: array<FactorioItembrowser\Api\Client\Entity\GenericEntity>
