FactorioItemBrowser\Api\Client\Response\Recipe\RecipeListResponse:
  exclusion_policy: all
  properties:
    recipes:
      type: array<FactorioItemBrowser\Api\Client\Transfer\RecipeWithExpensiveVersion>
    totalNumberOfResults:
      type: integer
