FactorioItemBrowser\Api\Client\Transfer\Recipe:
  exclusion_policy: all
  properties:
    mode:
      type: string
    ingredients:
      type: array<FactorioItemBrowser\Api\Client\Transfer\Item>
    products:
      type: array<FactorioItemBrowser\Api\Client\Transfer\Item>
    craftingTime:
      type: float
